version: "3.8"
services:
    mongodb:
        image: mongo:4.2.8
        container_name: my-test-mongo
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: "root"
        #     MONGO_INITDB_ROOT_PASSWORD: "devpwd"
        volumes:
            - ./db:/data/db
            - ./cloudBar:/data/dump
        ports:
            - "27017:27017"
        networks:
            botrista-dev:
                aliases:
                    - mongodb
        restart: always

networks:
    botrista-dev:

# for windows
volumes:
    mongodata:
        external: true